name: Deploy Web App - Reusable Workflow

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
        default: ubuntu-latest
      artifact-to-deploy:
        required: true
        type: string
      env-name:
        required: true
        type: string
      env-url:
        required: true
        type: string
      app-name:
        required: true
        type: string
      version-number:
        required: true
        type: string
  

jobs:
  deploy-web-app:

    
    name: Deploy to ${{ inputs.env-name }}
    
    runs-on: ${{ inputs.runs-on }}
    
    environment: 
      name: ${{ inputs.env-name }}
      url: ${{ inputs.env-url }}
    
    steps:
    
    - name: 'Login via Azure OIDC'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - uses: robinraju/release-downloader@v1.8
      with: 
        tag: ${{inputs.version-number}}
        fileName: "${{ inputs.artifact-to-deploy}}.zip"
        extract: false
    
    # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ inputs.app-name }}
        package: "${{ inputs.artifact-to-deploy}}.zip"
        

